# Generated by Django 4.2.1 on 2023-05-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=50)),
                ('Plot', models.CharField(max_length=255)),
                ('Director', models.CharField(max_length=50)),
                ('Actor', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
